import img from '../image/profile.png'


export const viewAllTips = [
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Buy",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "TEL13452",
        type: "Sell",
        stock_name: "Tata Steal",
        market_plan: "NSE - FO",
        market_type: "Swing",
        avg_price: "12.5-13.5",
        stop_loss1: "8.5",
        ref_level: "8.2",
        all_target: "Target 2 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Close",
        published: "Yes",
    },
    {
        tip_id: "JIO16829",
        type: "Buy",
        stock_name: "Reliance",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "2400-2420",
        stop_loss1: "2320",
        ref_level: "2385",
        all_target: "Target 3 - 18",
        stop_loss2: "SL -8.2",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
    {
        tip_id: "AIR1234",
        type: "Sell",
        stock_name: "Axis Bank",
        market_plan: "NSE - Cash",
        market_type: "Intraday",
        avg_price: "980-985",
        stop_loss1: "950.95",
        ref_level: "978.50",
        all_target: "Target 1 -1000",
        stop_loss2: "SL -920.55",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        status: "Open",
        published: "Yes",
    },
]


export const viewAllMarketPlan = [
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash -Option",
        exchange_code: "CDS - FUT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 1",
        quality: "20",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "MCX - Commodities - option",
        exchange_code: "MCX - OPT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 1",
        quality: "15",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Cash",
        exchange_code: "NFO -OPT",
        time_frame: "Swing",
        contract_type: "Option",
        automation: "Automation 2",
        quality: "10",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
    {
        market_plan: "NSE - Option",
        exchange_code: "CDS - FUT",
        time_frame: "Intraday",
        contract_type: "Future",
        automation: "Automation 4",
        quality: "5",
        default_plan: "Default",
        status: "Enable",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23"
    },
]


export const viewAllPriceAutomation = [
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash -Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "240.55",
        ref_target: "250",
        ref_stop_loss: "250",
        tg_1: "250",
        sl_1: "250",
        tg_2: "250",
        sl_2: "250",
        tg_3: "250",
        sl_3: "250",
        tg_4: "250",
        sl_4: "250",
        tg_5: "250",
        sl_5: "250",
        tg_6: "250",
        sl_6: "250",
        tg_7: "250",
        sl_7: "250",
        Status: "Enable"
    },
    {
        market_plan: "MCX - Commodities - option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "408.20",
        ref_target: "410",
        ref_stop_loss: "410",
        tg_1: "410",
        sl_1: "410",
        tg_2: "410",
        sl_2: "410",
        tg_3: "410",
        sl_3: "410",
        tg_4: "410",
        sl_4: "410",
        tg_5: "410",
        sl_5: "410",
        tg_6: "410",
        sl_6: "410",
        tg_7: "410",
        sl_7: "410",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Cash",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "674",
        ref_target: "694",
        ref_stop_loss: "694",
        tg_1: "694",
        sl_1: "694",
        tg_2: "694",
        sl_2: "694",
        tg_3: "694",
        sl_3: "694",
        tg_4: "694",
        sl_4: "694",
        tg_5: "694",
        sl_5: "694",
        tg_6: "694",
        sl_6: "694",
        tg_7: "694",
        sl_7: "694",
        Status: "Enable"
    },
    {
        market_plan: "NSE - Option",
        start_date: "29-Aug-23",
        end_date: "02-Sep-23",
        stop_loss: "145",
        ref_target: "167",
        ref_stop_loss: "167",
        tg_1: "167",
        sl_1: "167",
        tg_2: "167",
        sl_2: "167",
        tg_3: "167",
        sl_3: "167",
        tg_4: "167",
        sl_4: "167",
        tg_5: "167",
        sl_5: "167",
        tg_6: "167",
        sl_6: "167",
        tg_7: "167",
        sl_7: "167",
        Status: "Enable"
    },
]


export const viewAllMessageAutomation = [
    {
        title: "Atomisation 1",
        message_1: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_2: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_3: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_4: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_5: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_6: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_7: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets."
    },
    {
        title: "Atomisation 2",
        message_1: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_2: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_3: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_4: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_5: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_6: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets.",
        message_7: "Hit our target 1, now book 50 % profit here and trail your stop loss @ &  for remaining 50 % position and wait for next targets."
    },
]


export const allApplicationusers = [
    {
        user_id: 1,
        unique_code: "1693716939636",
        device_token: "e9MiJHui.....",
        user_name: "Harsh Jain",
        phone_no: "9039060804",
        device_type: "Android",
        membership_start: "28-aug-23",
        time: "12:45 AM",
        market_type: "NFO- OPT",
        rating: 5,
        total_click: 200,
        user_status: "Active",
        notification: "Enable",
        rewards: 250,
        last_login: "03-09-2023 10:25:39",
        status: "Enable"
    },
    {
        user_id: 2,
        unique_code: "1693716939636",
        device_token: "e9MiJHui.....",
        user_name: "Ravi jain",
        phone_no: "9039060804",
        device_type: "IOS",
        membership_start: "28-aug-23",
        time: "12:45 AM",
        market_type: "NFO- OPT",
        rating: 3.5,
        total_click: 240,
        user_status: "Active",
        notification: "Enable",
        rewards: 344,
        last_login: "03-09-2023 10:25:39",
        status: "Enable"
    },
    {
        user_id: 3,
        unique_code: "1693716939636",
        device_token: "e9MiJHui.....",
        user_name: "Prafful Gurjar",
        phone_no: "9039060804",
        device_type: "IOS",
        membership_start: "28-aug-23",
        time: "12:45 AM",
        market_type: "NFO- OPT",
        rating: 2.8,
        total_click: 372,
        user_status: "Active",
        notification: "Enable",
        rewards: 176,
        last_login: "03-09-2023 10:25:39",
        status: "Enable"
    },
    {
        user_id: 4,
        unique_code: "1693716939636",
        device_token: "e9MiJHui.....",
        user_name: "Yug Rajput",
        phone_no: "9039060804",
        device_type: "IOS",
        membership_start: "28-aug-23",
        time: "12:45 AM",
        market_type: "NFO- OPT",
        rating: 4.1,
        total_click: 614,
        user_status: "Active",
        notification: "Enable",
        rewards: 275,
        last_login: "03-09-2023 10:25:39",
        status: "Enable"
    },
]


export const traderClinicQueries = [
    {
        name: "Natasha jain",
        phone_no: "9039060804",
        script: "Silver",
        quality: "10,000 qty",
        avg_price: "60,000",
        position: "Long",
        comment: "shall I wait...",
        date_create: "28-aug-23 | 12:45",
        last_reply: "5-sep-23 | 10:25"
    },
    {
        name: "Anmol Sharma",
        phone_no: "9039060804",
        script: "Axis Bank",
        quality: "512 qty",
        avg_price: "1890",
        position: "Short",
        comment: "Buy on 287...",
        date_create: "18-aug-23 | 01:24",
        last_reply: "18-aug-23 | 01:24"
    },
    {
        name: "Shubham Rajput",
        phone_no: "9039060804",
        script: "Gold",
        quality: "20,101 qty",
        avg_price: "54,500",
        position: "Long",
        comment: "I buy at this....",
        date_create: "18-aug-23 | 01:24",
        last_reply: "2-sep-23 | 11:18"
    },
    {
        name: "Mansi Rajput",
        phone_no: "9039060804",
        script: "Silver",
        quality: "1000 qty",
        avg_price: "72,876",
        position: "Long",
        comment: "I buy at this....",
        date_create: "28-aug-23 | 12:45",
        last_reply: "4-sep-23 | 11:12"
    },
]


export const viewAllMembership = [
    {
        id: "1",
        plan_title: "MCX - Swing",
        plan: "Monthly",
        plan_category: "MCX - Commodities",
        plan_amount: "₹599",
        plan_days: "30 Days",
        tip_allowed: false,
        intraday: false,
        traders_clinic: true,
        message_created: "28-aug-23 | 12:45"
    },
    {
        id: "2",
        plan_title: "MCX - Intraday",
        plan: "Quarterly",
        plan_category: "Stock OPT",
        plan_amount: "₹1199",
        plan_days: "90 Days",
        tip_allowed: true,
        intraday: true,
        traders_clinic: true,
        message_created: "28-aug-23 | 12:45"
    },
    {
        id: "3",
        plan_title: "NSE - FUT",
        plan: "Yearly",
        plan_category: "Stock FUT",
        plan_amount: "₹1599",
        plan_days: "365 Days",
        tip_allowed: true,
        intraday: true,
        traders_clinic: true,
        message_created: "28-aug-23 | 12:45"
    },
    {
        id: "4",
        plan_title: "NSE - Cash",
        plan: "Quarterly",
        plan_category: "Cash",
        plan_amount: "₹1199",
        plan_days: "90 Days",
        tip_allowed: true,
        intraday: true,
        traders_clinic: false,
        message_created: "28-aug-23 | 12:45"
    },
]


export const viewAllCommentary = [
    {
        id: 1,
        comment_title: "Nifty Outlook of the day",
        description: "Nifty Future trade 19000....",
        message_created: "28-aug-23 | 12:45",
        image: img,
        status: "Published",
    },
    {
        id: 2,
        comment_title: "Bank Nifty Outlook",
        description: "Nifty Future trade 19000....",
        message_created: "28-aug-23 | 12:45",
        image: img,
        status: "Published",
    },
    {
        id: 3,
        comment_title: "Global Market Outlook",
        description: "Nifty Future trade 19000....",
        message_created: "28-aug-23 | 12:45",
        image: img,
        status: "Pending",
    },
    {
        id: 4,
        comment_title: "Global Market Outlook",
        description: "Nifty Future trade 19000....",
        message_created: "28-aug-23 | 12:45",
        image: img,
        status: "Published",
    },
    {
        id: 5,
        comment_title: "Tata steel Market",
        description: "Nifty Future trade 19000....",
        message_created: "28-aug-23 | 12:45",
        image: img,
        status: "Pending",
    },
]


export const viewFeedBack = [
    {
        id: 1,
        message_created: "28-aug-23 | 12:45",
        status: "Published"
    },
    {
        id: 2,
        message_created: "28-aug-23 | 12:45",
        status: "Published"
    },
    {
        id: 3,
        message_created: "28-aug-23 | 12:45",
        status: "Published"
    },
    {
        id: 4,
        message_created: "28-aug-23 | 12:45",
        status: "Pending"
    },
    {
        id: 5,
        message_created: "28-aug-23 | 12:45",
        status: "Published"
    },
    {
        id: 6,
        message_created: "28-aug-23 | 12:45",
        status: "Pending"
    },
    {
        id: 7,
        message_created: "28-aug-23 | 12:45",
        status: "Published"
    },
    {
        id: 8,
        message_created: "28-aug-23 | 12:45",
        status: "Pending"
    }
]